name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

      - name: download ckb
        run: |
          wget https://github.com/nervosnetwork/ckb/releases/download/v0.117.0/ckb_v0.117.0_x86_64-unknown-linux-gnu-portable.tar.gz
          tar -zxvf ckb_v0.117.0_x86_64-unknown-linux-gnu-portable.tar.gz
          cp ckb_v0.117.0_x86_64-unknown-linux-gnu-portable/ckb test

      - name: run ckb
        run: |
          cargo run --bin ckb-mock-miner-server -- -b 0.0.0.0:3000 -p ./mock.json > mock.log 2>&1 &

      - name: miner
        run: |
          cd test 
          ./ckb miner -l 5
